# Generated by Django 3.2.19 on 2024-05-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +525537048075', max_length=20, null=True),
        ),
    ]
