# Generated by Django 3.2.19 on 2024-04-22 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0004_alter_reporteciudadano_referencia_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesTrabajador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.reportetrabajador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesCiudadano',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.reporteciudadano')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
