# Generated by Django 3.2.19 on 2024-05-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20240509_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesciudadano',
            name='valido',
            field=models.BooleanField(default=False),
        ),
    ]
