# Generated by Django 3.2.19 on 2024-04-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcaldia',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('alcaldia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('alcaldia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.alcaldia')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBache',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteTrabajador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=23)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=23)),
                ('estado_reporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.estadoreporte')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.prioridad')),
                ('tipo_bache', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.tipobache')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteCiudadano',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=23)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=23)),
                ('num_ext', models.IntegerField()),
                ('num_int', models.IntegerField()),
                ('cp', models.IntegerField(max_length=5)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia_adicional', models.CharField(max_length=200)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.calle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
