# Generated by Django 3.2.19 on 2024-04-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20240420_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportetrabajador',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.calle'),
        ),
    ]
