# Generated by Django 3.2.19 on 2024-04-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reportetrabajador_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteciudadano',
            name='referencia_adicional',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
