# Generated by Django 3.2.19 on 2024-05-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reporteciudadano_referencia_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteciudadano',
            name='latitud',
            field=models.DecimalField(decimal_places=7, max_digits=23),
        ),
        migrations.AlterField(
            model_name='reporteciudadano',
            name='longitud',
            field=models.DecimalField(decimal_places=7, max_digits=23),
        ),
        migrations.AlterField(
            model_name='reportetrabajador',
            name='latitud',
            field=models.DecimalField(decimal_places=7, max_digits=23),
        ),
        migrations.AlterField(
            model_name='reportetrabajador',
            name='longitud',
            field=models.DecimalField(decimal_places=7, max_digits=23),
        ),
    ]
