# Generated by Django 3.2.19 on 2024-05-30 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0006_auto_20240509_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteciudadano',
            name='modo',
            field=models.CharField(default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='reportetrabajador',
            name='cp',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='reportetrabajador',
            name='modo',
            field=models.CharField(default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporteciudadano',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reporteciudadano',
            name='num_ext',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reporteciudadano',
            name='num_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reporteciudadano',
            name='referencia_adicional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ReporteTiempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=23)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=23)),
                ('image', models.ImageField(default=None, upload_to='imagenes_tr/')),
                ('cp', models.IntegerField(default=0, max_length=5)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.calle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
