# Generated by Django 3.2.19 on 2024-05-30 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_auto_20240530_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportetiemporeal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
